      - name: Live Now
        run: |
          SOURCE="https://vpsttt.vietanhtv.top/tv360/tv360.php?id=99"
          end=$((SECONDS + 10200))
          
          while [ $SECONDS -lt $end ]; do
            echo "========== Khởi động lại luồng FFmpeg =========="
            
            ffmpeg -y \
              -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
              -headers "Referer: https://vietanhtv.id.vn/" \
              -re -i "$SOURCE" \
              -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3500k -bufsize 6000k \
              -pix_fmt yuv420p -g 60 -keyint_min 60 -sc_threshold 0 \
              -c:a aac -b:a 128k -ar 44100 \
              -f flv "rtmps://live.twitch.tv/app/${{ secrets.TWITCH_KEY_5 }}"
            
            echo "Lỗi hoặc ngắt kết nối. Đang thử lại sau 5 giây..."
            sleep 5
          done
