name: FFmpeg Fix Mixed Content
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */3 * * *' # Tự động làm mới mỗi 3 tiếng

jobs:
  ffmpeg-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Convert HTTP to HTTPS Stream
        run: |
          # Dùng -protocol_whitelist để cho phép FFmpeg đọc cả http và https cùng lúc
          ffmpeg -hide_banner -loglevel error \
          -protocol_whitelist file,http,https,tcp,tls \
          -headers "Referer: https://vietanhtv.id.vn/" \
          -i "https://vietanhtv.id.vn/tv360/32/index.m3u8" \
          -t 60 -c copy -f hls -hls_time 10 -hls_list_size 6 -y index.m3u8
          
          sleep 5

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.m3u8
          git commit --allow-empty -m "Fix Mixed Content & Reset 3h - $(date)"
          git push
