Name: Stream_Pro_TV_Style

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Live
        run: |
          export TZ="Asia/Ho_Chi_Minh"
          ffmpeg -re -stream_loop -1 -i "https://vietanhtv.id.vn/tv360/32/index.m3u8" \
          -vf "drawtext=text='%{localtime\:%H\\\\\:%M\\\\\:%S}':fontcolor=white:fontsize=45:x=W-w-20:y=H-th-20:box=1:boxcolor=black@0.6:boxborderw=10" \
          -c:v libx264 -preset veryfast -b:v 3000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -f flv \
          "rtmp://live.twitch.tv/app/${{ secrets.TWITCH_KEY }}"
