name: Stream_VieON_DongNai3

on:
  schedule:
    - cron: '0 */3 * * *' # Tự động chạy lại mỗi 3 tiếng cố định
  workflow_dispatch: # Chỉ chạy khi bạn chủ động bấm nút kích hoạt bằng tay

jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install FFmpeg Fast
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y ffmpeg

    - name: Live Now
      env:
        STREAM_KEY: ${{ secrets.TWITCH_KEY_3 }}
      run: |
        if [ -z "$STREAM_KEY" ]; then
          echo "⚠️ Lỗi: Không tìm thấy Secret TWITCH_KEY_3."
          exit 1
        fi

        SOURCE="https://sgclient.duckdns.org/source/vieon.m3u8?id=dongnai3"
        end=$((SECONDS + 10200))
        
        while [ $SECONDS -lt $end ]; do
          echo "========== [Đồng Nai 3] Đang đẩy luồng trực tiếp... =========="
          
          ffmpeg -re -loglevel error \
            -fflags +genpts+discardcorrupt \
            -analyzeduration 1500000 -probesize 1000000 \
            -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 \
            -reconnect_delay_max 10 -rw_timeout 15000000 \
            -headers "Referer: https://vietanhtv.id.vn/"$'\r\n'"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -i "$SOURCE" \
            -c:v copy -c:a copy \
            -f flv "rtmps://live.twitch.tv/app/$STREAM_KEY"
            
          echo "Kết nối bị ngắt. Tự động kết nối lại sau 5 giây..."
          sleep 5
        done
