name: Livestream_Matrix_Super_Light

on:
  schedule:
    # Tự động khởi động lại sau mỗi 3 tiếng để dọn cache và làm mới luồng phát
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-stream:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - id: 1
            name: "Kenh_VieON_DongNai3"
            source_url: "https://sgclient.duckdns.org/source/vieon.m3u8?id=dongnai3"
            key_position: 1 # Đứng đầu tiên: Đọc mã Key số 1 trong chuỗi Secret
          
          - id: 2
            name: "Kenh_TV360_Id32"
            source_url: "https://sgclient.duckdns.org/source/tv360.m3u8?id=32"
            key_position: 2 # Đứng ở giữa: Đọc mã Key số 2 trong chuỗi Secret
          
          - id: 3
            name: "Kenh_TV360_Id175"
            source_url: "https://sgclient.duckdns.org/source/tv360.m3u8?id=175"
            key_position: 3 # Đứng sau cùng: Đọc mã Key số 3 trong chuỗi Secret

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install FFmpeg Fast
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y ffmpeg

    - name: Live Now
      env:
        RAW_KEYS: ${{ secrets.ALL_TWITCH_KEYS }}
      run: |
        # Trích xuất chính xác Stream Key theo thứ tự bạn đã sắp xếp
        STREAM_KEY=$(echo "$RAW_KEYS" | cut -d',' -f${{ matrix.key_position }})

        if [ -z "$STREAM_KEY" ]; then
          echo "⚠️ Lỗi: Không lấy được Stream Key ở vị trí thứ ${{ matrix.key_position }}. Dừng luồng."
          exit 0
        fi

        echo "========== Khởi động máy ảo số ${{ matrix.id }} phát luồng: ${{ matrix.name }} =========="
        end=$((SECONDS + 10200))
        
        while [ $SECONDS -lt $end ]; do
          echo "---- Đang đẩy luồng trực tiếp sang Twitch ----"
          
          ffmpeg -re \
            -fflags +genpts+discardcorrupt \
            -analyzeduration 1500000 -probesize 1000000 \
            -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 \
            -reconnect_delay_max 10 -rw_timeout 15000000 \
            -headers "Referer: https://vietanhtv.id.vn/"$'\r\n'"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -i "${{ matrix.source_url }}" \
            -c:v copy -c:a copy \
            -f flv "rtmps://live.twitch.tv/app/$STREAM_KEY"
            
          echo "Mất kết nối. Tự động khởi động lại sau 5 giây..."
          sleep 5
        done
