name: Bam Mot Nut - Chay 3 Luong Giua

on:
  workflow_dispatch:
  schedule:
    # Chạy lại định kỳ mỗi 5 tiếng 50 phút
    - cron: '50 */5 * * *'

jobs:
  # Kích hoạt đồng thời 3 file workflow con
  chay-dongnai3:
    uses: ./.github/workflows/dongnai3.yml

  chay-livestream:
    uses: ./.github/workflows/livestream.yml

  chay-static:
    uses: ./.github/workflows/static.yml
